name: Deploy Frontend

on:
    push:
        branches:
        - main
        paths:
        - 'frontend/**'  
    workflow_dispatch:

jobs:
    deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
        uses: actions/checkout@v4

    - name: Deploy Frontend via Rsync
        uses: easingthemes/ssh-deploy@main
        env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz --delete --exclude='.git/'"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT || 22 }}
        SOURCE: "frontend/"        
        TARGET: ${{ secrets.REMOTE_FRONTEND_TARGET_PATH }}  